name: Run LIT testsuite
inputs:
  arch:
    required: true
runs:
  using: composite
  steps:

    - name: 'Posix: Run LIT testsuite'
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -eux

        if [[ '${{ runner.os }}-${{ inputs.arch }}' == Linux-aarch64 ]]; then
          # FIXME: the following tests fail
          rm tests/debuginfo/nested_gdb.d
          rm tests/debuginfo/print_gdb.d # works for Cirrus CI though
          rm tests/sanitizers/fuzz_basic.d
        fi

        cd ../build
        # temporarily add LLVM bin dir to PATH, so that e.g. wasm-ld is found
        PATH="$PWD/../llvm/bin:$PATH" ctest -V -R "lit-tests"

    - name: 'Windows: Run LIT testsuite'
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo on
        :: FIXME: strings_cdb has regressed for 32-bit starting with the VS 2019 v16.6.0 Azure Image (worked fine until v16.5.4)
        ::        it also works fine on my box with the same v16.7.2...
        if "${{ inputs.arch }}" == "x86" (
          del tests\debuginfo\strings_cdb.d || exit /b
        )
        call "%LDC_VSDIR%\Common7\Tools\VsDevCmd.bat" -arch=${{ inputs.arch }} || exit /b
        echo on
        cd ..\build || exit /b
        ctest -V -R "lit-tests" || exit /b
